language: python
python:
  - 2.7
  - 3.5

install:
  - pip install coveralls
  - pip install flake8
  - pip install nose

script:
  - flake8
  - nosetests --with-coverage

after_success:
  - coveralls
